/* Garnish drink data — part 1
   Format: [name, category, glass, method, color, base, description, ingredients[], garnish, extras{}]
   Ingredient: "amount|unit|Ingredient Name|flags|note"   flags: opt, top, float, side, foam, glass
*/
window.DRINKS = [
// ───────── MARTINIS ─────────
["Gin Martini","Martini","martini","stir","#e9e4c9","Gin","The king of cocktails. Crisp, cold, bone-dry and dangerously elegant.",
 ["2.5|oz|Gin","0.5|oz|Dry Vermouth","1|dash|Orange Bitters|opt"],"Lemon twist or olives"],
["Vesper","Martini","martini","shake","#efe6b8","Gin","James Bond's own invention from Casino Royale — gin, vodka and Lillet, shaken (yes, shaken).",
 ["3|oz|Gin","1|oz|Vodka","0.5|oz|Lillet Blanc"],"Large thin lemon peel",{post:["Bond insists it be shaken until ice-cold. Who are we to argue with a fictional spy?"]}],
["Dirty Martini","Martini","martini","stir","#d9d3a6","Vodka","A martini that rolled around in the olive jar. Briny, savory, and unapologetic. Works with gin or vodka.",
 ["2.5|oz|Vodka||or Gin","0.5|oz|Dry Vermouth","0.5|oz|Olive Brine"],"2–3 olives on a pick"],
["Dill Pickle Martini","Martini","martini","shake","#cfd9a0","Vodka","For people who drink the pickle juice straight from the jar. Tangy, salty, gloriously weird.",
 ["2.5|oz|Vodka","0.75|oz|Pickle Brine||dill pickle juice","0.25|oz|Dry Vermouth"],"Pickle spear or mini gherkin"],
["Pear Martini","Martini","martini","shake","#e8e3a2","Vodka","Soft, juicy, autumn-in-a-glass. Pear vodka with a squeeze of lemon and a whisper of sweetness.",
 ["2|oz|Pear Vodka","1|oz|Pear Nectar","0.5|oz|Pear Liqueur|opt|St-George Spiced Pear or similar","0.5|oz|Lemon Juice","0.25|oz|Simple Syrup"],"Thin pear slice"],
["Espresso Martini","Martini","martini","shake","#3b2416","Vodka","Wakes you up and winds you down at the same time. The drink equivalent of a plot twist.",
 ["2|oz|Vodka","1|oz|Espresso||freshly brewed, cooled slightly","0.5|oz|Coffee Liqueur","0.25|oz|Simple Syrup"],"3 coffee beans",{post:["Shake extra hard — the crema foam on top comes from aggressive shaking."]}],
["Cosmopolitan","Martini","martini","shake","#e0466a","Vodka","The Cosmo. Tart, pink, and forever associated with four friends in Manhattan.",
 ["1.5|oz|Citrus Vodka","1|oz|Triple Sec||Cointreau ideal","0.5|oz|Lime Juice","0.75|oz|Cranberry Juice"],"Flamed orange peel or lime wheel"],
["Sour Apple Martini","Martini","martini","shake","#9fe03a","Vodka","The Appletini. Neon green, mouth-puckering, and proudly 2003.",
 ["1.5|oz|Vodka","1|oz|Sour Apple Schnapps","0.5|oz|Lemon Juice","0.25|oz|Simple Syrup|opt"],"Thin green apple slice"],
["Vodka Martini","Martini","martini","stir","#eef0f0","Vodka","Clean, cold, and as smooth as a well-pressed tux.",
 ["2.5|oz|Vodka","0.5|oz|Dry Vermouth"],"Lemon twist or olive"],
["Gibson","Martini","martini","stir","#ece8cf","Gin","A gin martini that swapped the olive for a cocktail onion. Savory and sharp.",
 ["2.5|oz|Gin","0.5|oz|Dry Vermouth"],"Cocktail onions on a pick"],
["Lemon Drop Martini","Martini","martini","shake","#f3e46a","Vodka","Sweet-tart lemon candy for grown-ups, with a sugared rim.",
 ["2|oz|Citrus Vodka","0.5|oz|Triple Sec","1|oz|Lemon Juice","0.5|oz|Simple Syrup"],"Sugar rim and lemon twist",{pre:["Rub a lemon wedge around the rim of the glass and dip it in sugar."]}],
["French Martini","Martini","martini","shake","#c2416b","Vodka","Velvety pineapple froth with a raspberry blush. Fancy but friendly.",
 ["2|oz|Vodka","0.5|oz|Raspberry Liqueur||Chambord","1.5|oz|Pineapple Juice"],"Raspberry or lemon twist"],
["Pornstar Martini","Martini","coupe","shake","#f2b134","Vodka","Passion fruit and vanilla, served with a sidecar shot of bubbly. Yes, that's really the name.",
 ["1.5|oz|Vanilla Vodka","0.5|oz|Passion Fruit Liqueur||Passoã","1|oz|Passion Fruit Purée","0.5|oz|Lime Juice","0.25|oz|Vanilla Syrup","2|oz|Sparkling Wine|side|served in a shot glass on the side"],"Half a passion fruit, floating",{post:["Sip the drink and the bubbly alternately."]}],
["Chocolate Martini","Martini","martini","shake","#5a3420","Vodka","Dessert in a stemmed glass. Rich, creamy, and frankly a little smug.",
 ["1.5|oz|Vodka","1|oz|Crème de Cacao","1|oz|Irish Cream","0.5|oz|Heavy Cream|opt"],"Chocolate syrup swirl and shaved chocolate",{pre:["Drizzle chocolate syrup in a spiral inside the chilled glass."]}],
["Martinez","Martini","coupe","stir","#a2482a","Gin","The martini's sweeter, older grandpa. Gin meets sweet vermouth and maraschino.",
 ["1.5|oz|Gin||Old Tom style if you have it","1.5|oz|Sweet Vermouth","0.25|oz|Maraschino Liqueur","2|dash|Angostura Bitters"],"Orange twist"],
["Breakfast Martini","Martini","martini","shake","#f0b545","Gin","A martini with a spoonful of orange marmalade. Legally counts as breakfast (it does not).",
 ["2|oz|Gin","0.5|oz|Triple Sec","0.75|oz|Lemon Juice","1|barspoon|Orange Marmalade"],"Orange twist; toast optional"],
["Pomegranate Martini","Martini","martini","shake","#9e1b3a","Vodka","Deep ruby, tart, and a little bit dramatic.",
 ["1.5|oz|Vodka","0.5|oz|Triple Sec","1.5|oz|Pomegranate Juice","0.5|oz|Lime Juice"],"Pomegranate seeds"],
["Key Lime Pie Martini","Martini","martini","shake","#dfeaa3","Vodka","A whole slice of Key lime pie, minus the fork. Graham cracker rim mandatory.",
 ["1.5|oz|Vanilla Vodka","1|oz|Lime Juice","1|oz|Heavy Cream","0.5|oz|Simple Syrup","0.5|oz|Pineapple Juice"],"Graham cracker rim and lime wheel",{pre:["Wet the rim with lime and dip in crushed graham crackers."]}],
["Violet Ginny","Martini","coupe","shake","#8d6bc9","Gin","A floral gin sour kissed with crème de violette — lavender-purple, bright and lightly sparkling. (House build.)",
 ["2|oz|Gin","0.5|oz|Crème de Violette","0.75|oz|Lemon Juice","0.5|oz|Simple Syrup","1|oz|Club Soda|top"],"Lemon twist or an edible flower"],
["Aviation","Martini","coupe","shake","#b9a6d8","Gin","A sky-blue pre-Prohibition classic. Floral, tart, and named after flying machines.",
 ["2|oz|Gin","0.5|oz|Maraschino Liqueur","0.25|oz|Crème de Violette","0.75|oz|Lemon Juice"],"Brandied cherry"],
["Corpse Reviver #2","Martini","coupe","shake","#efe3a1","Gin","A hangover 'cure' from the 1930s. Four of these 'will unrevive the corpse again.'",
 ["0.75|oz|Gin","0.75|oz|Lillet Blanc","0.75|oz|Triple Sec","0.75|oz|Lemon Juice","1|rinse|Absinthe"],"Orange twist",{pre:["Rinse the chilled glass with absinthe and dump out the excess."]}],
["Last Word","Martini","coupe","shake","#b5c95a","Gin","Equal parts, perfectly balanced, very green. A Prohibition-era banger revived in Seattle.",
 ["0.75|oz|Gin","0.75|oz|Green Chartreuse","0.75|oz|Maraschino Liqueur","0.75|oz|Lime Juice"],"Brandied cherry"],
["Hanky Panky","Martini","coupe","stir","#7a2c1e","Gin","Created by Ada Coleman at the Savoy. Gin, sweet vermouth and a bossy hit of Fernet.",
 ["1.5|oz|Gin","1.5|oz|Sweet Vermouth","2|barspoon|Fernet-Branca"],"Orange twist"],
["Bijou","Martini","coupe","stir","#9c6a1c","Gin","'Jewel' in French — gin, sweet vermouth and green Chartreuse in a gleaming amber.",
 ["1|oz|Gin","1|oz|Sweet Vermouth","1|oz|Green Chartreuse","1|dash|Orange Bitters"],"Cherry and lemon twist"],
["Bamboo","Martini","coupe","stir","#e3c77a","Wine","A low-proof, sherry-based aperitif from 1890s Yokohama. Delicate and nutty.",
 ["1.5|oz|Dry Sherry||fino or amontillado","1.5|oz|Dry Vermouth","2|dash|Orange Bitters","1|dash|Angostura Bitters"],"Lemon twist"],

// ───────── STIRRED CLASSICS ─────────
["Old Fashioned","Classic","rocks","custom","#b8641c","Whiskey","The original 'cocktail': spirit, sugar, water, bitters. Timeless as a leather armchair.",
 ["2|oz|Bourbon||or Rye Whiskey","1|cube|Sugar Cube||or 0.25 oz Demerara Syrup","3|dash|Angostura Bitters","1|splash|Club Soda|opt|or a few drops of water"],"Orange peel and a cherry",
 {steps:["Drop the sugar cube into a rocks glass and soak it with the bitters and a tiny splash of soda or water.","Muddle until the sugar dissolves into a gritty paste.","Add the bourbon and one large ice cube.","Stir for 20–30 seconds to chill and dilute.","Express an orange peel over the glass (squeeze it skin-side down so the oils mist the drink), then drop it in with a cherry."]}],
["Manhattan","Classic","coupe","stir","#8a2e17","Whiskey","Rye, sweet vermouth, and bitters. Sophisticated, a little spicy, and named after the borough.",
 ["2|oz|Rye Whiskey","1|oz|Sweet Vermouth","2|dash|Angostura Bitters"],"Brandied cherry"],
["Perfect Manhattan","Classic","coupe","stir","#a2461e","Whiskey","A Manhattan split evenly between sweet and dry vermouth. Perfectly balanced, hence the name.",
 ["2|oz|Rye Whiskey","0.5|oz|Sweet Vermouth","0.5|oz|Dry Vermouth","2|dash|Angostura Bitters"],"Lemon twist"],
["Black Manhattan","Classic","coupe","stir","#3a1a10","Whiskey","Swap vermouth for bittersweet amaro. Darker, moodier, more interesting at parties.",
 ["2|oz|Rye Whiskey","1|oz|Averna||or another dark amaro","1|dash|Angostura Bitters","1|dash|Orange Bitters"],"Brandied cherry"],
["Rob Roy","Classic","coupe","stir","#8c3a1a","Whiskey","A Manhattan wearing a kilt. Scotch, sweet vermouth, bitters.",
 ["2|oz|Scotch Whisky","1|oz|Sweet Vermouth","2|dash|Angostura Bitters"],"Cherry"],
["Negroni","Classic","rocks","stirR","#c3301c","Gin","Equal parts gin, Campari and sweet vermouth. Bitter, bold, and gorgeously red.",
 ["1|oz|Gin","1|oz|Campari","1|oz|Sweet Vermouth"],"Orange peel or half wheel"],
["Mezcal Negroni","Classic","rocks","stirR","#b22d1c","Tequila","A Negroni that sat by a campfire. Smoky and bittersweet.",
 ["1|oz|Mezcal","1|oz|Campari","1|oz|Sweet Vermouth"],"Orange peel"],
["White Negroni","Classic","rocks","stirR","#ece2a0","Gin","A pale, floral Negroni with gentian Suze and Lillet instead of red bitters.",
 ["1.5|oz|Gin","1|oz|Lillet Blanc","0.75|oz|Suze"],"Lemon twist"],
["Negroni Sbagliato","Bubbly","rocks","build","#cf3d22","Wine","'Mistaken' Negroni — someone grabbed bubbly instead of gin. Best mistake ever.",
 ["1|oz|Campari","1|oz|Sweet Vermouth","2|oz|Sparkling Wine|top|Prosecco"],"Orange half-wheel"],
["Boulevardier","Classic","rocks","stirR","#9a2b17","Whiskey","A Negroni with bourbon instead of gin — warmer, rounder, cozier.",
 ["1.5|oz|Bourbon","1|oz|Campari","1|oz|Sweet Vermouth"],"Orange twist"],
["Old Pal","Classic","coupe","stir","#c0592a","Whiskey","Rye, Campari and dry vermouth. A drier, spicier cousin of the Boulevardier.",
 ["1.5|oz|Rye Whiskey","0.75|oz|Campari","0.75|oz|Dry Vermouth"],"Lemon twist"],
["Americano","Highball","highball","build","#c4472a","Liqueur","Campari, sweet vermouth and soda. Low-proof, bittersweet, sunny-afternoon fuel.",
 ["1.5|oz|Campari","1.5|oz|Sweet Vermouth","3|oz|Club Soda|top"],"Orange half-wheel"],
["Sazerac","Classic","rocks","custom","#b04a24","Whiskey","New Orleans' official cocktail. Rye, Peychaud's, and a ghostly whisper of absinthe.",
 ["2|oz|Rye Whiskey","1|cube|Sugar Cube||or 0.25 oz Simple Syrup","3|dash|Peychaud's Bitters","1|dash|Angostura Bitters|opt","1|rinse|Absinthe"],"Lemon peel (expressed, then discarded)",
 {steps:["Chill a rocks glass with ice water.","In a mixing glass, muddle the sugar cube with the bitters and a few drops of water.","Add the rye, fill with ice and stir for 30 seconds.","Dump the ice water from the serving glass, add the absinthe, swirl to coat the inside and discard the excess.","Strain the drink into the absinthe-rinsed glass — no ice.","Express a lemon peel over the top and discard it (traditional) or drop it in (rebellious)."]}],
["Vieux Carré","Classic","rocks","stirR","#9c4a1f","Whiskey","Named for the French Quarter. Rye, cognac, vermouth, Bénédictine — rich and layered.",
 ["0.75|oz|Rye Whiskey","0.75|oz|Cognac","0.75|oz|Sweet Vermouth","1|barspoon|Bénédictine","1|dash|Peychaud's Bitters","1|dash|Angostura Bitters"],"Cherry or lemon twist"],
["Brooklyn","Classic","coupe","stir","#a3471f","Whiskey","Manhattan's neighbor across the river — rye, dry vermouth, maraschino and amaro.",
 ["2|oz|Rye Whiskey","1|oz|Dry Vermouth","0.25|oz|Maraschino Liqueur","0.25|oz|Amer Picon||or Amaro CioCiaro"],"Cherry"],
["Rusty Nail","Classic","rocks","stirR","#b56a1d","Whiskey","Scotch and Drambuie. Honeyed, herbal, and very Rat Pack.",
 ["2|oz|Scotch Whisky","0.75|oz|Drambuie"],"Lemon twist"],
["Godfather","Classic","rocks","stirR","#9c5a1f","Whiskey","Scotch and amaretto. An offer you can't refuse.",
 ["2|oz|Scotch Whisky","0.75|oz|Amaretto"],"None needed"],
["Stinger","Classic","coupe","shake","#e8e0c2","Brandy","Brandy and white crème de menthe — a minty, after-dinner sting.",
 ["2|oz|Cognac","0.75|oz|White Crème de Menthe"],"Mint sprig"],
["El Presidente","Classic","coupe","stir","#d35a2a","Rum","A 1920s Havana classic. Rum, blanc vermouth, orange curaçao and a dash of grenadine.",
 ["1.5|oz|White Rum","0.75|oz|Dry Vermouth||blanc vermouth ideal","0.5|oz|Orange Curaçao","1|barspoon|Grenadine"],"Orange twist"],
["Black Russian","Classic","rocks","build","#2a160c","Vodka","Vodka and coffee liqueur. Simple, dark, and mysterious.",
 ["2|oz|Vodka","1|oz|Coffee Liqueur"],"None"],
["White Russian","Dessert","rocks","build","#e8d6bc","Vodka","The Dude abides. A Black Russian with a creamy cloud on top.",
 ["2|oz|Vodka","1|oz|Coffee Liqueur","1|oz|Heavy Cream|float"],"None (bathrobe optional)"],
["Oaxaca Old Fashioned","Classic","rocks","stirR","#c07a2a","Tequila","Reposado tequila and mezcal in an Old Fashioned. Smoky, earthy, modern classic.",
 ["1.5|oz|Tequila Reposado","0.5|oz|Mezcal","1|barspoon|Agave Syrup","2|dash|Angostura Bitters"],"Flamed orange peel"],
["Rum Old Fashioned","Classic","rocks","stirR","#a85a1e","Rum","Aged rum gives this Old Fashioned caramel and tropical spice.",
 ["2|oz|Aged Rum","0.25|oz|Demerara Syrup","2|dash|Angostura Bitters","1|dash|Orange Bitters"],"Orange peel"],

// ───────── SOURS & SHAKEN CLASSICS ─────────
["Daiquiri","Sour","coupe","shake","#eef0c8","Rum","Rum, lime, sugar. Three ingredients, zero hiding. The bartender's handshake.",
 ["2|oz|White Rum","1|oz|Lime Juice","0.75|oz|Simple Syrup"],"Lime wheel"],
["Hemingway Daiquiri","Sour","coupe","shake","#f0d9b0","Rum","Papa Doble — extra rum, grapefruit and maraschino, no sugar. Hemingway's way.",
 ["2|oz|White Rum","0.75|oz|Lime Juice","0.5|oz|Grapefruit Juice","0.5|oz|Maraschino Liqueur"],"Lime wheel"],
["Whiskey Sour","Sour","rocks","dry","#e7b75a","Whiskey","Bourbon, lemon, sugar and a silky egg-white foam. A crowd-pleaser since the 1860s.",
 ["2|oz|Bourbon","0.75|oz|Lemon Juice","0.75|oz|Simple Syrup","1|whole|Egg White|opt","2|dash|Angostura Bitters|opt,foam|dotted on the foam"],"Cherry and Angostura dots on the foam"],
["New York Sour","Sour","rocks","custom","#a0283a","Whiskey","A Whiskey Sour wearing a red wine float. Stunning layers.",
 ["2|oz|Rye Whiskey","1|oz|Lemon Juice","0.75|oz|Simple Syrup","1|whole|Egg White|opt","0.5|oz|Red Wine||dry, fruity (Malbec, Shiraz)"],"Lemon wheel",
 {steps:["Add rye, lemon, syrup and egg white (if using) to a shaker without ice. Dry shake 10 seconds.","Add ice and shake hard for another 12–15 seconds.","Strain into a rocks glass over fresh ice.","Hold a bar spoon upside down just above the drink and slowly pour the red wine over the back so it floats in a crimson layer."]}],
["Amaretto Sour","Sour","rocks","dry","#e0952e","Liqueur","Jeffrey Morgenthaler's fix for a much-maligned drink: amaretto plus a backbone of bourbon.",
 ["1.5|oz|Amaretto","0.75|oz|Bourbon","1|oz|Lemon Juice","1|tsp|Simple Syrup","1|whole|Egg White|opt"],"Lemon peel and brandied cherries"],
["Pisco Sour","Sour","coupe","dry","#efe5c5","Brandy","Peru and Chile both claim it. Pisco, lime, sugar, egg white, and bitters art on top.",
 ["2|oz|Pisco","1|oz|Lime Juice","0.75|oz|Simple Syrup","1|whole|Egg White","3|drop|Angostura Bitters|foam|on the foam"],"Bitters drops on the foam"],
["Gimlet","Sour","coupe","shake","#e3efc0","Gin","Gin and lime — sharp, bracing, and a favorite of British sailors fighting scurvy.",
 ["2|oz|Gin","0.75|oz|Lime Juice","0.75|oz|Simple Syrup"],"Lime wheel"],
["Vodka Gimlet","Sour","coupe","shake","#e6f0c8","Vodka","The Gimlet's cleaner, quieter twin.",
 ["2|oz|Vodka","0.75|oz|Lime Juice","0.75|oz|Simple Syrup"],"Lime wheel"],
["Sidecar","Sour","coupe","shake","#e1a34a","Brandy","Cognac, orange liqueur and lemon in a sugared glass. Born in post-WWI Paris.",
 ["2|oz|Cognac","0.75|oz|Triple Sec||Cointreau ideal","0.75|oz|Lemon Juice"],"Sugar rim and orange twist",{pre:["Half-rim the glass with sugar (so guests can choose sweet or not)."]}],
["Between the Sheets","Sour","coupe","shake","#e7b25b","Brandy","A Sidecar that snuck rum in. Cheeky name, serious drink.",
 ["1|oz|Cognac","1|oz|White Rum","1|oz|Triple Sec","0.25|oz|Lemon Juice"],"Lemon twist"],
["Bee's Knees","Sour","coupe","shake","#f2d36b","Gin","Prohibition slang for 'the best.' Gin, lemon and honey — buzzworthy.",
 ["2|oz|Gin","0.75|oz|Lemon Juice","0.75|oz|Honey Syrup"],"Lemon twist"],
["Gold Rush","Sour","rocks","shakeR","#e3a83a","Whiskey","A modern classic: bourbon, honey and lemon. A Whiskey Sour that struck gold.",
 ["2|oz|Bourbon","0.75|oz|Honey Syrup","0.75|oz|Lemon Juice"],"Lemon wheel"],
["Brown Derby","Sour","coupe","shake","#e0a050","Whiskey","Hollywood, 1930s. Bourbon, grapefruit and honey.",
 ["2|oz|Bourbon","1|oz|Grapefruit Juice","0.5|oz|Honey Syrup"],"Grapefruit twist"],
["Penicillin","Sour","rocks","custom","#e1ad48","Whiskey","Scotch, honey-ginger and lemon with a peaty float. Cures what ails you (allegedly).",
 ["2|oz|Scotch Whisky||blended","0.75|oz|Lemon Juice","0.75|oz|Honey-Ginger Syrup","0.25|oz|Islay Scotch||float"],"Candied ginger",
 {steps:["Add blended Scotch, lemon juice and honey-ginger syrup to a shaker.","Fill with ice and shake hard for 12–15 seconds.","Strain into a rocks glass over a large ice cube.","Gently float the Islay Scotch on top by pouring it over the back of a bar spoon — the smoky aroma hits your nose first.","Garnish with candied ginger on a pick."]}],
["Paper Plane","Sour","coupe","shake","#e18a3a","Whiskey","Four equal parts — bourbon, Aperol, Amaro Nonino and lemon. Named for an M.I.A. song.",
 ["0.75|oz|Bourbon","0.75|oz|Aperol","0.75|oz|Amaro Nonino","0.75|oz|Lemon Juice"],"Tiny paper plane (optional but encouraged)"],
["Clover Club","Sour","coupe","dry","#e88a9a","Gin","Pink, frothy and Philadelphian. Gin, raspberry, lemon and egg white.",
 ["1.5|oz|Gin","0.5|oz|Dry Vermouth","0.5|oz|Lemon Juice","0.5|oz|Raspberry Syrup","1|whole|Egg White"],"3 raspberries on a pick"],
["White Lady","Sour","coupe","dry","#f2efe0","Gin","Gin, Cointreau, lemon and egg white. Pristine and elegant.",
 ["2|oz|Gin","0.5|oz|Triple Sec","0.75|oz|Lemon Juice","0.5|oz|Egg White|opt"],"Lemon twist"],
["Jack Rose","Sour","coupe","shake","#e05a5a","Brandy","Applejack, lemon and grenadine. A rosy American classic.",
 ["2|oz|Apple Brandy","0.75|oz|Lemon Juice","0.5|oz|Grenadine"],"Apple slice"],
["Ward Eight","Sour","coupe","shake","#e47a4a","Whiskey","Boston, 1898. Rye with lemon, orange and a hint of grenadine.",
 ["2|oz|Rye Whiskey","0.5|oz|Lemon Juice","0.5|oz|Orange Juice","0.25|oz|Grenadine"],"Orange twist and cherry"],
["Bramble","Sour","rocks","custom","#7a1f4a","Gin","1980s London. Gin sour on crushed ice with a blackberry liqueur 'bleed'.",
 ["2|oz|Gin","1|oz|Lemon Juice","0.5|oz|Simple Syrup","0.5|oz|Crème de Mûre||blackberry liqueur"],"Blackberries and lemon wheel",
 {steps:["Shake gin, lemon and simple syrup with ice for 10 seconds.","Strain into a rocks glass packed with crushed ice.","Slowly drizzle the crème de mûre over the top so it bleeds down through the ice like a bramble.","Garnish with blackberries and a lemon wheel."]}],
["Southside","Sour","coupe","muddle","#cbe8a5","Gin","A minty gin sour — basically a Mojito in a tux. Rumored favorite of Al Capone's crew.",
 ["2|oz|Gin","0.75|oz|Lime Juice","0.75|oz|Simple Syrup","6|leaves|Mint Leaves"],"Mint sprig"],
["Midori Sour","Sour","highball","shakeR","#76d65a","Liqueur","Neon melon nostalgia. Sweet, sour, and impossibly green.",
 ["1.5|oz|Melon Liqueur","0.5|oz|Vodka","0.5|oz|Lemon Juice","0.5|oz|Lime Juice","1|oz|Club Soda|top"],"Lemon wheel and cherry"],
["Blood and Sand","Sour","coupe","shake","#c8462a","Whiskey","Named for a 1922 bullfighter film. Scotch, cherry, vermouth, OJ — weird but wonderful.",
 ["0.75|oz|Scotch Whisky","0.75|oz|Cherry Heering","0.75|oz|Sweet Vermouth","0.75|oz|Orange Juice"],"Orange peel"],
["Mary Pickford","Sour","coupe","shake","#f08a8a","Rum","Rum, pineapple and maraschino — named for the silent-film star.",
 ["2|oz|White Rum","1.5|oz|Pineapple Juice","1|barspoon|Grenadine","1|barspoon|Maraschino Liqueur"],"Brandied cherry"],
["Twentieth Century","Sour","coupe","shake","#efe0b5","Gin","Named after the luxury train. Gin, Lillet, white cacao and lemon — chocolatey and crisp.",
 ["1.5|oz|Gin","0.75|oz|Lillet Blanc","0.5|oz|Crème de Cacao||white","0.75|oz|Lemon Juice"],"Lemon twist"],
["Bacardi Cocktail","Sour","coupe","shake","#f2a3a8","Rum","Rum, lime and grenadine — a pink Daiquiri that once had a lawsuit about its name.",
 ["2|oz|White Rum","0.75|oz|Lime Juice","0.5|oz|Grenadine"],"Lime wheel"],
["Naked and Famous","Sour","coupe","shake","#f0a548","Tequila","Smoky mezcal meets Aperol and yellow Chartreuse. Equal parts and very modern.",
 ["0.75|oz|Mezcal","0.75|oz|Aperol","0.75|oz|Yellow Chartreuse","0.75|oz|Lime Juice"],"None"],
["Cable Car","Sour","coupe","shake","#e0a043","Rum","Spiced rum sidecar with a cinnamon-sugar rim. San Francisco, 1996.",
 ["1.5|oz|Spiced Rum","0.75|oz|Orange Curaçao","1|oz|Lemon Juice","0.5|oz|Simple Syrup"],"Cinnamon-sugar rim and orange spiral",{pre:["Rim the glass with a mix of cinnamon and sugar."]}],
["Kamikaze","Shot","coupe","shake","#e6efc8","Vodka","Vodka, triple sec and lime. Usually a shot; great as a mini martini too.",
 ["1|oz|Vodka","1|oz|Triple Sec","1|oz|Lime Juice"],"Lime wedge"],
["Whiskey Smash","Sour","rocks","custom","#d8b44a","Whiskey","Muddled lemon and mint with bourbon over crushed ice. Bright and summery.",
 ["2|oz|Bourbon","0.75|oz|Simple Syrup","3|wedge|Lemon","6|leaves|Mint Leaves"],"Mint sprig",
 {steps:["Muddle the lemon wedges in a shaker to release juice and oils.","Add the mint leaves and press gently (don't shred them — bitter mint is sad mint).","Add bourbon and syrup, fill with ice and shake for 10 seconds.","Double-strain into a rocks glass over crushed ice.","Garnish with a big slapped mint sprig."]}],

// ───────── MARGARITAS & AGAVE ─────────
["Classic Margarita","Sour","margarita","shakeR","#e6ec9e","Tequila","Tequila, lime, orange liqueur and a salt rim. The undisputed party starter.",
 ["2|oz|Tequila Blanco","1|oz|Lime Juice","0.75|oz|Triple Sec||Cointreau ideal","0.25|oz|Agave Syrup|opt"],"Salt rim and lime wheel",{pre:["Run a lime wedge around the outer rim of the glass and dip it in coarse salt."]}],
["Spicy Margarita","Sour","rocks","custom","#d6e86a","Tequila","A Margarita with a jalapeño kick. Sweat optional, joy guaranteed.",
 ["2|oz|Tequila Blanco","1|oz|Lime Juice","0.5|oz|Triple Sec","0.5|oz|Agave Syrup","3|slice|Jalapeño"],"Tajín rim and jalapeño wheel",
 {steps:["Rim a rocks glass with Tajín or chili-salt using a lime wedge.","Muddle the jalapeño slices in a shaker (2 slices = mild, 4 = brave).","Add tequila, lime, triple sec and agave, then fill with ice.","Shake hard for 12–15 seconds.","Double-strain over fresh ice in the rimmed glass so no seeds sneak through.","Garnish with a jalapeño wheel."]}],
["Tommy's Margarita","Sour","rocks","shakeR","#e3ea9a","Tequila","No orange liqueur — just tequila, lime and agave. Pure and agave-forward.",
 ["2|oz|Tequila Blanco","1|oz|Lime Juice","0.5|oz|Agave Syrup"],"Lime wheel, salt optional"],
["Frozen Margarita","Frozen","margarita","blend","#e4f0b0","Tequila","The slushy, brain-freezing poolside legend.",
 ["2|oz|Tequila Blanco","1|oz|Triple Sec","1|oz|Lime Juice","0.75|oz|Simple Syrup"],"Salt rim and lime wheel",{pre:["Salt the rim of a margarita glass."]}],
["Cadillac Margarita","Sour","margarita","shakeR","#e6c46a","Tequila","Reposado tequila with a Grand Marnier float. The luxury model.",
 ["2|oz|Tequila Reposado","1|oz|Lime Juice","0.5|oz|Agave Syrup","0.5|oz|Grand Marnier|float"],"Salt rim and lime wheel"],
["Strawberry Margarita","Frozen","margarita","blend","#e8475a","Tequila","Blended strawberries plus margarita magic. Pink and party-ready.",
 ["2|oz|Tequila Blanco","1|oz|Triple Sec","1|oz|Lime Juice","5|whole|Strawberries","0.5|oz|Simple Syrup"],"Sugar rim and strawberry"],
["Paloma","Highball","highball","build","#f4b2a0","Tequila","Mexico's favorite highball: tequila, lime and grapefruit soda. Easy and electric.",
 ["2|oz|Tequila Blanco","0.5|oz|Lime Juice","5|oz|Grapefruit Soda|top|Squirt or Jarritos"],"Salt rim and lime wedge"],
["Ranch Water","Highball","highball","build","#eef3e8","Tequila","West Texas in a glass. Tequila, lime, and a LOT of Topo Chico.",
 ["2|oz|Tequila Blanco","0.75|oz|Lime Juice","5|oz|Club Soda|top|Topo Chico mineral water ideal"],"Lime wheel"],
["Tequila Sunrise","Highball","highball","custom","#f3842a","Tequila","Orange-to-red gradient like a Mexican sunrise. Thanks, 1970s.",
 ["2|oz|Tequila Blanco","4|oz|Orange Juice","0.5|oz|Grenadine"],"Orange slice and cherry",
 {steps:["Fill a highball glass with ice.","Pour in the tequila, then the orange juice, and give it a quick stir.","Slowly pour the grenadine down the inside edge of the glass — it'll sink to the bottom.","Do NOT stir. Admire your sunrise.","Garnish with an orange slice and cherry."]}],
["Batanga","Highball","highball","build","#4a2010","Tequila","Tequila and Mexican Coke in a salt-rimmed glass, stirred with a knife (tradition!).",
 ["2|oz|Tequila Blanco","0.5|oz|Lime Juice","5|oz|Cola|top|Mexican Coca-Cola ideal"],"Salt rim and lime wedge"],
["Mexican Mule","Highball","mule","build","#e8d7a0","Tequila","A Moscow Mule that crossed the border.",
 ["2|oz|Tequila Blanco","0.5|oz|Lime Juice","4|oz|Ginger Beer|top"],"Lime wheel"],
["Bloody Maria","Highball","highball","custom","#b8301e","Tequila","A Bloody Mary with tequila instead of vodka. Earthier, spicier.",
 ["2|oz|Tequila Blanco","4|oz|Tomato Juice","0.5|oz|Lime Juice","2|dash|Worcestershire Sauce","2|dash|Hot Sauce","1|pinch|Celery Salt","1|pinch|Black Pepper"],"Lime wedge, celery, jalapeño",
 {steps:["Rim a highball glass with celery salt and fill with ice.","Add all ingredients to a shaker with ice.","'Roll' the drink: pour it back and forth between two tins 4–5 times (shaking makes tomato juice foamy).","Strain into the glass and garnish generously."]}],
["Carajillo","Classic","rocks","shakeR","#5a3218","Liqueur","Mexico's after-dinner favorite: Licor 43 and fresh espresso shaken over ice.",
 ["2|oz|Licor 43","1.5|oz|Espresso||freshly brewed"],"Orange peel or coffee beans",{post:["Prefer it layered? Pour Licor 43 over ice and slowly pour hot espresso over the back of a spoon."]}],
["Mexican Candy Shot","Shot","shot","shake","#e0473a","Tequila","Tastes like a chili-watermelon lollipop. Tajín rim required.",
 ["1|oz|Tequila Blanco","0.5|oz|Watermelon Schnapps","0.25|oz|Lime Juice","1|dash|Hot Sauce||Tapatío or Valentina"],"Tajín rim",{pre:["Rim shot glasses with Tajín."]}],

// ───────── VODKA & HIGHBALLS ─────────
["Moscow Mule","Highball","mule","build","#e7d79c","Vodka","Vodka, ginger beer and lime in an ice-cold copper mug. Zingy and refreshing.",
 ["2|oz|Vodka","0.5|oz|Lime Juice","4|oz|Ginger Beer|top"],"Lime wheel and mint sprig"],
["Kentucky Mule","Highball","mule","build","#d9b46a","Whiskey","Bourbon takes the Mule to the Derby.",
 ["2|oz|Bourbon","0.5|oz|Lime Juice","4|oz|Ginger Beer|top"],"Mint sprig and lime"],
["Bloody Mary","Highball","highball","custom","#b52a1c","Vodka","The brunch MVP. Savory, spicy, and basically a salad.",
 ["2|oz|Vodka","4|oz|Tomato Juice","0.5|oz|Lemon Juice","2|dash|Worcestershire Sauce","2|dash|Hot Sauce","1|tsp|Horseradish|opt","1|pinch|Celery Salt","1|pinch|Black Pepper"],"Celery stalk, lemon, olives, pickle, bacon — go wild",
 {steps:["Rim a highball glass with celery salt and fill with ice.","Add vodka, tomato juice, lemon, Worcestershire, hot sauce, horseradish, celery salt and pepper to a shaker with ice.","Roll the drink: pour back and forth between two tins 4–5 times to mix without making it foamy.","Strain into the glass.","Garnish like you're building a tiny edible skyscraper."]}],
["Caesar","Highball","highball","custom","#c0452a","Vodka","Canada's national cocktail — a Bloody Mary made with Clamato.",
 ["1.5|oz|Vodka","4|oz|Clamato","2|dash|Worcestershire Sauce","2|dash|Hot Sauce","1|pinch|Celery Salt","1|pinch|Black Pepper"],"Celery salt rim, celery stalk, lime wedge",
 {steps:["Rim a highball glass with celery salt and fill with ice.","Add vodka, Worcestershire, hot sauce and pepper.","Top with Clamato and stir well.","Garnish with a celery stalk and lime wedge. Say 'sorry' politely."]}],
["Screwdriver","Highball","highball","build","#f6a52a","Vodka","Vodka and OJ. Legend says oil workers stirred it with screwdrivers.",
 ["2|oz|Vodka","5|oz|Orange Juice"],"Orange slice"],
["Harvey Wallbanger","Highball","highball","custom","#f3a72e","Vodka","A Screwdriver with a Galliano float. Named after a surfer who wiped out a lot.",
 ["1.5|oz|Vodka","4|oz|Orange Juice","0.5|oz|Galliano"],"Orange slice and cherry",
 {steps:["Fill a highball glass with ice.","Add vodka and orange juice, then stir.","Float the Galliano on top by pouring it over the back of a bar spoon.","Garnish and try not to bang into any walls."]}],
["Greyhound","Highball","highball","build","#f5c3b0","Vodka","Vodka and grapefruit. Tart, clean, simple.",
 ["2|oz|Vodka","5|oz|Grapefruit Juice"],"Grapefruit wedge"],
["Salty Dog","Highball","highball","build","#f5c8b5","Gin","A Greyhound with a salted rim — gin or vodka both work.",
 ["2|oz|Gin||or Vodka","5|oz|Grapefruit Juice"],"Salt rim and grapefruit wedge",{pre:["Rim the glass with coarse salt."]}],
["Cape Codder","Highball","highball","build","#c8243e","Vodka","Vodka cranberry with a squeeze of lime. Simple and Massachusetts-approved.",
 ["2|oz|Vodka","4|oz|Cranberry Juice","0.25|oz|Lime Juice|opt"],"Lime wedge"],
["Sea Breeze","Highball","highball","build","#ec7c86","Vodka","Vodka, cranberry and grapefruit. Like a beach in July.",
 ["1.5|oz|Vodka","3|oz|Cranberry Juice","1.5|oz|Grapefruit Juice"],"Lime wedge"],
["Bay Breeze","Highball","highball","build","#f09a8a","Vodka","The Sea Breeze's tropical cousin — swaps grapefruit for pineapple.",
 ["1.5|oz|Vodka","3|oz|Cranberry Juice","1.5|oz|Pineapple Juice"],"Pineapple wedge"],
["Madras","Highball","highball","build","#e8603a","Vodka","Vodka with cranberry and orange — named after the colorful plaid.",
 ["1.5|oz|Vodka","3|oz|Cranberry Juice","1.5|oz|Orange Juice"],"Lime wedge"],
["Sex on the Beach","Highball","highball","build","#f2703a","Vodka","Peach, cranberry and orange. Sunset-colored and suggestively named.",
 ["1.5|oz|Vodka","0.5|oz|Peach Schnapps","2|oz|Cranberry Juice","2|oz|Orange Juice"],"Orange slice and cherry"],
["Fuzzy Navel","Highball","highball","build","#f8b04a","Liqueur","Peach schnapps and OJ. Fuzzy (peach) plus navel (orange). Very '80s.",
 ["2|oz|Peach Schnapps","4|oz|Orange Juice"],"Orange slice"],
["Long Island Iced Tea","Highball","collins","build","#a8622a","Vodka","Five spirits, zero tea, maximum chaos. Tastes innocent; is not.",
 ["0.5|oz|Vodka","0.5|oz|Gin","0.5|oz|White Rum","0.5|oz|Tequila Blanco","0.5|oz|Triple Sec","0.75|oz|Lemon Juice","0.5|oz|Simple Syrup","1|oz|Cola|top"],"Lemon wedge",{post:["The splash of cola gives it the iced-tea color. Pace yourself."]}],
["Long Beach Iced Tea","Highball","collins","build","#c8344a","Vodka","Long Island's West Coast cousin — cranberry instead of cola.",
 ["0.5|oz|Vodka","0.5|oz|Gin","0.5|oz|White Rum","0.5|oz|Tequila Blanco","0.5|oz|Triple Sec","0.75|oz|Lemon Juice","0.5|oz|Simple Syrup","1|oz|Cranberry Juice|top"],"Lemon wedge"],
["Adios (AMF)","Highball","collins","build","#2a8fe0","Vodka","An electric-blue Long Island that says goodbye to your evening plans.",
 ["0.5|oz|Vodka","0.5|oz|Gin","0.5|oz|White Rum","0.5|oz|Tequila Blanco","0.5|oz|Blue Curaçao","1|oz|Lemon Juice","0.5|oz|Simple Syrup","2|oz|Lemon-Lime Soda|top"],"Lemon wedge and cherry"],
["Electric Lemonade","Highball","collins","build","#3aa8e8","Vodka","Blue, fizzy, glowing lemonade. Looks like it charges your phone.",
 ["1.5|oz|Vodka","0.5|oz|Blue Curaçao","1|oz|Lemon Juice","0.5|oz|Simple Syrup","3|oz|Lemon-Lime Soda|top"],"Lemon wheel"],
["Blue Lagoon","Highball","hurricane","build","#2fa0e6","Vodka","Vodka, blue curaçao and lemonade. Lagoon-blue and suspiciously chuggable.",
 ["1.5|oz|Vodka","1|oz|Blue Curaçao","4|oz|Lemonade|top"],"Lemon wheel and cherry"],
["Gin and Tonic","Highball","wine","build","#eef3ec","Gin","The G&T. Bitter quinine, botanical gin, lots of ice. Perfection in two ingredients.",
 ["2|oz|Gin","4|oz|Tonic Water|top"],"Lime wedge (or cucumber, or grapefruit)",{post:["Pro tip: pour the tonic down a bar spoon to keep the bubbles lively."]}],
["Tom Collins","Highball","collins","build","#eef1d8","Gin","A sparkling gin lemonade. Tall, cold and refreshingly polite.",
 ["2|oz|Gin","1|oz|Lemon Juice","0.5|oz|Simple Syrup","3|oz|Club Soda|top"],"Lemon wheel and cherry",{pre:["Shake the gin, lemon and syrup briefly with ice first for a better mix (optional)."]}],
["John Collins","Highball","collins","build","#ebdcaa","Whiskey","The Tom Collins with bourbon instead of gin.",
 ["2|oz|Bourbon","1|oz|Lemon Juice","0.5|oz|Simple Syrup","3|oz|Club Soda|top"],"Lemon wheel and cherry"],
["Gin Fizz","Sour","highball","dry","#f1efdf","Gin","A frothy, fizzy gin sour served without ice. Bubbly and bright.",
 ["2|oz|Gin","0.75|oz|Lemon Juice","0.75|oz|Simple Syrup","1|whole|Egg White|opt","2|oz|Club Soda|top"],"Lemon twist"],
["Ramos Gin Fizz","Sour","collins","custom","#f6f3e6","Gin","New Orleans legend: shaken for minutes until it rises above the glass like a cloud.",
 ["2|oz|Gin","0.5|oz|Lemon Juice","0.5|oz|Lime Juice","0.75|oz|Simple Syrup","1|oz|Heavy Cream","1|whole|Egg White","3|drop|Orange Flower Water","2|oz|Club Soda|top"],"None — the foam is the garnish",
 {steps:["Add everything except the soda to a shaker. Dry shake (no ice) for 15 seconds.","Add a few ice cubes and shake HARD for 1–2 minutes. Yes, really. Put on music.","Strain into a chilled Collins glass with no ice.","Let it rest 1 minute so the foam sets.","Slowly pour the club soda into the center — watch the foam rise above the rim. Push a straw straight through the middle."]}],
["Gin Rickey","Highball","highball","build","#eef3e0","Gin","Gin, fresh lime and soda — no sugar. Bone-dry and invigorating.",
 ["2|oz|Gin","0.75|oz|Lime Juice","4|oz|Club Soda|top"],"Lime shell dropped in"],
["Southern Bramble","Highball","collins","build","#7b2a4c","Whiskey","Bourbon lemonade with a blackberry swirl. (House twist on a Bramble.)",
 ["1.5|oz|Bourbon","0.75|oz|Lemon Juice","0.5|oz|Simple Syrup","0.5|oz|Crème de Mûre","2|oz|Club Soda|top"],"Blackberries and lemon"],
["Mojito","Highball","collins","custom","#d8efc0","Rum","Cuba's minty, limey, sparkly treasure. Muddle gently — mint bruises easily.",
 ["2|oz|White Rum","1|oz|Lime Juice","0.75|oz|Simple Syrup","8|leaves|Mint Leaves","2|oz|Club Soda|top"],"Mint sprig and lime wheel",
 {steps:["Drop the mint leaves and simple syrup into a Collins glass.","Gently press the mint with a muddler — just enough to release the oils, not shred it.","Add lime juice and rum.","Fill the glass with crushed ice and swizzle (spin a bar spoon between your palms) to mix.","Top with club soda and a bit more crushed ice.","Slap a mint sprig between your hands to wake it up, then tuck it next to the straw."]}],
["Cuba Libre","Highball","highball","build","#4b2212","Rum","Rum and Coke with fresh lime. 'Free Cuba!' since 1900.",
 ["2|oz|White Rum","0.5|oz|Lime Juice","4|oz|Cola|top"],"Lime wedge"],
["Dark 'n' Stormy","Highball","highball","custom","#5a3418","Rum","Bermuda's storm cloud: ginger beer with a dark rum float. Trademarked, delicious.",
 ["2|oz|Dark Rum||Gosling's Black Seal is traditional","0.5|oz|Lime Juice|opt","4|oz|Ginger Beer"],"Lime wedge",
 {steps:["Fill a highball glass with ice.","Pour in the ginger beer (and lime, if using).","Slowly float the dark rum on top so it billows down like storm clouds.","Garnish with a lime wedge and serve unstirred."]}],
["Japanese Highball","Highball","highball","custom","#f0d898","Whiskey","Whisky and very cold, very bubbly soda. A meditative ritual.",
 ["1.5|oz|Japanese Whisky","4.5|oz|Club Soda|top|very cold"],"Lemon peel",
 {steps:["Fill a chilled highball glass to the top with ice.","Stir for a few seconds to chill the glass, then pour off any melt water.","Add the whisky and stir 13 times (a ritual in Japanese bars).","Top up the ice, then pour the soda gently down a bar spoon to preserve bubbles.","Stir once, vertically. Express a lemon peel over the top."]}],
["Seven and Seven","Highball","highball","build","#e7c88a","Whiskey","Seagram's 7 Crown and 7-Up. Lucky number twice.",
 ["2|oz|Blended Whiskey||Seagram's 7 Crown","4|oz|Lemon-Lime Soda|top|7-Up"],"Lemon wedge"],
["Whiskey Ginger","Highball","highball","build","#d8b06a","Whiskey","Whiskey and ginger ale. Easiest drink to order in any bar.",
 ["2|oz|Whiskey||Irish whiskey is great here — any whiskey works","4|oz|Ginger Ale|top"],"Lime or lemon wedge"],
["Whiskey and Coke","Highball","highball","build","#4a2414","Whiskey","Whiskey, cola, ice. The dive-bar handshake.",
 ["2|oz|Whiskey||any — bourbon or Tennessee whiskey is classic","4|oz|Cola|top"],"Lemon or lime wedge (optional)"],
["Horse's Neck","Highball","highball","build","#d9a050","Brandy","Brandy and ginger ale with a long, dramatic lemon peel spiral hanging out of the glass.",
 ["2|oz|Cognac||or Bourbon","4|oz|Ginger Ale|top","2|dash|Angostura Bitters|opt"],"One long lemon peel spiral",{pre:["Cut one continuous spiral of lemon peel and coil it inside the glass, letting it hang over the rim."]}],
["Mint Julep","Classic","julep","custom","#cfe2a5","Whiskey","Kentucky Derby royalty. Bourbon, mint and mountains of crushed ice.",
 ["2.5|oz|Bourbon","0.5|oz|Simple Syrup","8|leaves|Mint Leaves"],"Big bouquet of mint and a short straw",
 {steps:["Gently muddle the mint with the simple syrup in a julep cup (or rocks glass).","Add the bourbon and fill halfway with crushed ice. Stir until the cup frosts.","Pack more crushed ice on top into a dome.","Slap a big mint bouquet and tuck it in right next to a short straw — you want to smell the mint with every sip."]}],
["Pimm's Cup","Highball","collins","build","#b8642a","Liqueur","The official drink of Wimbledon. Fruity, herbal, and very British.",
 ["2|oz|Pimm's No. 1","0.5|oz|Lemon Juice","4|oz|Ginger Ale|top|or British-style lemonade"],"Cucumber, strawberry, orange and mint"],
["Aperol Spritz","Bubbly","wine","build","#f5772a","Liqueur","The 3-2-1 sunset of Italian aperitivo. Bubbly, bittersweet orange.",
 ["3|oz|Sparkling Wine||Prosecco","2|oz|Aperol","1|oz|Club Soda|top"],"Orange half-wheel",{post:["Pour Prosecco first, then Aperol, so it mixes itself."]}],
["Hugo Spritz","Bubbly","wine","build","#e8f0c8","Wine","Elderflower, mint and Prosecco — the Aperol Spritz's floral alpine cousin.",
 ["4|oz|Sparkling Wine||Prosecco","1|oz|Elderflower Liqueur","1|oz|Club Soda|top","5|leaves|Mint Leaves"],"Mint sprig and lime wheel"],
["Limoncello Spritz","Bubbly","wine","build","#f6e260","Liqueur","Amalfi Coast sunshine — limoncello, Prosecco and soda.",
 ["2|oz|Limoncello","3|oz|Sparkling Wine||Prosecco","1|oz|Club Soda|top"],"Lemon wheel and mint"],
["White Wine Spritzer","Bubbly","wine","build","#f3eccb","Wine","White wine and soda. Light, bubbly, brunch-safe.",
 ["4|oz|White Wine","2|oz|Club Soda|top"],"Lemon twist"],
["French 75","Bubbly","flute","shake","#f2e6a8","Gin","Named after a WWI field gun because it hits that hard. Gin, lemon and Champagne.",
 ["1|oz|Gin","0.5|oz|Lemon Juice","0.5|oz|Simple Syrup","3|oz|Sparkling Wine|top|Champagne"],"Long lemon twist"],
["Kir Royale","Bubbly","flute","build","#7a1d3a","Wine","Champagne blushing with crème de cassis. Instantly fancy.",
 ["0.5|oz|Crème de Cassis","5|oz|Sparkling Wine|top|Champagne"],"Blackberry or lemon twist"],
["Bellini","Bubbly","flute","custom","#f7c08a","Wine","Venice's Harry's Bar classic: white peach purée topped with Prosecco.",
 ["2|oz|Peach Purée","4|oz|Sparkling Wine||Prosecco"],"Peach slice",
 {steps:["Pour the peach purée into a chilled flute.","Slowly add the Prosecco, tilting the glass so it doesn't fizz over.","Stir gently once with a bar spoon to blend."]}],
["Mimosa","Bubbly","flute","build","#f8b440","Wine","Bubbly and OJ. Brunch's official mascot.",
 ["3|oz|Sparkling Wine","3|oz|Orange Juice|top"],"Orange twist"],
["Champagne Cocktail","Bubbly","flute","custom","#f0d690","Wine","A bitters-soaked sugar cube fizzing at the bottom of a flute. Old-school glamour.",
 ["1|cube|Sugar Cube","3|dash|Angostura Bitters","0.5|oz|Cognac|opt","5|oz|Sparkling Wine||Champagne"],"Lemon twist",
 {steps:["Place the sugar cube on a napkin and soak it with bitters.","Drop it into a chilled flute (add cognac now if using).","Slowly top with Champagne and watch the cube release a steady stream of bubbles."]}],
["Death in the Afternoon","Bubbly","flute","build","#e4f0d0","Wine","Hemingway's recipe: absinthe topped with Champagne 'until it attains the proper opalescent milkiness.'",
 ["1.5|oz|Absinthe","4.5|oz|Sparkling Wine|top|Champagne"],"None"],
["Air Mail","Bubbly","coupe","shake","#f3d68a","Rum","A rum French 75 with honey. Cuban, airy, delightful.",
 ["1.5|oz|Aged Rum","0.75|oz|Lime Juice","0.75|oz|Honey Syrup","2|oz|Sparkling Wine|top"],"Lime wheel"],
["Frosé","Frozen","wine","custom","#f69aa8","Wine","Frozen rosé slushie — Instagram's favorite summer drink.",
 ["8|oz|Rosé Wine","1|oz|Lemon Juice","1|oz|Simple Syrup","4|whole|Strawberries"],"Strawberry",
 {steps:["Pour the rosé into an ice cube tray and freeze at least 6 hours (it won't freeze rock-solid — that's normal).","Add the rosé cubes, strawberries, lemon juice and syrup to a blender.","Blend until slushy and smooth.","Pour into wine glasses and garnish with a strawberry."]}],
];
/* Garnish drink data — part 2 */
window.DRINKS.push(
// ───────── TIKI & TROPICAL ─────────
["Piña Colada","Tiki","hurricane","blend","#f6ecc6","Rum","Puerto Rico's creamy pineapple-coconut dream. If you like getting caught in the rain…",
 ["2|oz|White Rum","3|oz|Pineapple Juice","1.5|oz|Coconut Cream||Coco López","0.5|oz|Lime Juice|opt"],"Pineapple wedge and cherry"],
["Mai Tai","Tiki","rocks","shakeR","#e0952f","Rum","Trader Vic's 1944 masterpiece. 'Maita'i' means 'good' in Tahitian — understatement.",
 ["1|oz|Aged Rum","1|oz|Dark Rum||Jamaican","0.75|oz|Lime Juice","0.5|oz|Orange Curaçao","0.5|oz|Orgeat","0.25|oz|Simple Syrup"],"Spent lime shell and a big mint sprig",{post:["Serve over crushed ice; the spent lime half floating on top is the traditional 'island' garnish."]}],
["Zombie","Tiki","tiki","custom","#c8541f","Rum","Don the Beachcomber's legendary three-rum monster. Limit: two per customer. Seriously.",
 ["1.5|oz|Dark Rum||Jamaican","1.5|oz|Aged Rum","1|oz|Overproof Rum||151 proof","0.75|oz|Lime Juice","0.5|oz|Falernum","0.5|oz|Grapefruit Juice","0.5|oz|Cinnamon Syrup","1|tsp|Grenadine","1|dash|Angostura Bitters","6|drop|Absinthe"],"Mint sprig",
 {steps:["Add everything except the overproof rum to a blender with 6 oz crushed ice.","Flash-blend for 5 seconds (or shake hard with crushed ice).","Pour unstrained into a tall tiki mug.","Float the overproof rum on top.","Add more crushed ice if needed and garnish with a mint sprig. Respect the two-drink limit."]}],
["Painkiller","Tiki","tiki","shakeR","#f1c574","Rum","Born on a British Virgin Island bar you had to swim to. Rum, pineapple, orange, coconut and nutmeg.",
 ["2|oz|Dark Rum||Pusser's","4|oz|Pineapple Juice","1|oz|Orange Juice","1|oz|Coconut Cream"],"Fresh grated nutmeg and pineapple wedge"],
["Jungle Bird","Tiki","rocks","shakeR","#c7442a","Rum","1970s Kuala Lumpur. Dark rum and Campari make this tiki drink bittersweet.",
 ["1.5|oz|Dark Rum||blackstrap","0.75|oz|Campari","1.5|oz|Pineapple Juice","0.5|oz|Lime Juice","0.5|oz|Simple Syrup"],"Pineapple wedge and fronds"],
["Hurricane","Tiki","hurricane","shakeR","#e8452e","Rum","Pat O'Brien's New Orleans party fuel — passion fruit and two rums.",
 ["2|oz|White Rum","2|oz|Dark Rum","1|oz|Passion Fruit Purée","1|oz|Orange Juice","0.5|oz|Lime Juice","0.5|oz|Simple Syrup","1|tbsp|Grenadine"],"Orange slice and cherry"],
["Planter's Punch","Tiki","collins","shakeR","#d8642a","Rum","'One of sour, two of sweet, three of strong, four of weak.' Jamaica's rhyme in a glass.",
 ["3|oz|Dark Rum||Jamaican","1|oz|Lime Juice","0.75|oz|Simple Syrup","0.25|oz|Grenadine","3|dash|Angostura Bitters","1|oz|Club Soda|top"],"Orange slice, cherry, mint"],
["Rum Punch","Punch","hurricane","shakeR","#ea5a36","Rum","Caribbean party juice. Two rums, three juices, one great time.",
 ["1|oz|White Rum","1|oz|Dark Rum","2|oz|Pineapple Juice","2|oz|Orange Juice","0.5|oz|Lime Juice","0.5|oz|Grenadine"],"Orange and cherry flag"],
["Blue Hawaii","Tiki","hurricane","shakeR","#2aa7e3","Rum","Electric blue and Elvis-approved.",
 ["0.75|oz|White Rum","0.75|oz|Vodka","0.5|oz|Blue Curaçao","3|oz|Pineapple Juice","1|oz|Lemon Juice","0.5|oz|Simple Syrup"],"Pineapple wedge and cocktail umbrella"],
["Bahama Mama","Tiki","hurricane","shakeR","#ef6f3a","Rum","Coconut rum, dark rum and fruit punch vibes. A vacation for your face.",
 ["1|oz|Coconut Rum","1|oz|Dark Rum","2|oz|Pineapple Juice","1|oz|Orange Juice","0.5|oz|Lemon Juice","0.5|oz|Grenadine"],"Pineapple wedge and cherry"],
["Rum Runner","Tiki","hurricane","shakeR","#e0472f","Rum","Florida Keys smuggler fuel with banana and blackberry.",
 ["1|oz|Spiced Rum","1|oz|Dark Rum","0.5|oz|Banana Liqueur","0.5|oz|Crème de Mûre","2|oz|Pineapple Juice","1|oz|Orange Juice","0.25|oz|Grenadine"],"Orange slice and cherry"],
["Scorpion","Tiki","tiki","shakeR","#f0a24a","Rum","A Trader Vic sharer: rum, brandy, orgeat and citrus. Sting included.",
 ["1.5|oz|White Rum","0.5|oz|Cognac","1.5|oz|Orange Juice","1|oz|Lemon Juice","0.75|oz|Orgeat"],"Gardenia or orange slice"],
["Singapore Sling","Tiki","hurricane","shakeR","#e8566a","Gin","Raffles Hotel, 1915. Gin, cherry, pineapple, Bénédictine — fruity and complex.",
 ["1.5|oz|Gin","0.5|oz|Cherry Heering","0.25|oz|Triple Sec","0.25|oz|Bénédictine","4|oz|Pineapple Juice","0.5|oz|Lime Juice","0.33|oz|Grenadine","1|dash|Angostura Bitters"],"Pineapple wedge and cherry"],
["Banana Daiquiri","Frozen","hurricane","blend","#f3e19a","Rum","A frozen Daiquiri that went bananas.",
 ["2|oz|White Rum","1|whole|Banana||ripe","1|oz|Lime Juice","0.75|oz|Simple Syrup","0.5|oz|Banana Liqueur|opt"],"Banana slice"],
["Strawberry Daiquiri","Frozen","hurricane","blend","#e83f52","Rum","The frozen pink classic of swim-up bars everywhere.",
 ["2|oz|White Rum","6|whole|Strawberries","1|oz|Lime Juice","0.75|oz|Simple Syrup"],"Strawberry"],
["Miami Vice","Frozen","hurricane","custom","#f08a8a","Rum","Half Piña Colada, half Strawberry Daiquiri, 100% neon '80s.",
 ["3|oz|White Rum","4|whole|Strawberries","0.75|oz|Lime Juice","0.5|oz|Simple Syrup","2|oz|Pineapple Juice","1.5|oz|Coconut Cream"],"Pineapple wedge and strawberry",
 {steps:["Blend half the rum with the strawberries, lime and syrup plus 1 cup ice. Pour into a pitcher.","Rinse the blender. Blend the other half of the rum with pineapple juice and coconut cream plus 1 cup ice.","Tilt a hurricane glass and pour both at the same time from opposite sides for a swirl — or layer one on top of the other.","Garnish and put on your sunglasses at night."]}],
["Mudslide","Dessert","hurricane","blend","#7a4a2a","Vodka","A boozy chocolate milkshake. Basically dessert with a driver's license.",
 ["1|oz|Vodka","1|oz|Coffee Liqueur","1|oz|Irish Cream","2|scoop|Vanilla Ice Cream","0.5|oz|Chocolate Syrup|glass|swirled inside the glass"],"Chocolate syrup swirl and whipped cream",{pre:["Swirl chocolate syrup inside the glass."]}],
["Caipirinha","Classic","rocks","custom","#e6f0b5","Brandy","Brazil's national cocktail — cachaça, muddled lime and sugar.",
 ["2|oz|Cachaça","1|whole|Lime||cut into 8 wedges","2|tsp|Sugar"],"Lime wedge",
 {steps:["Cut the lime into wedges and remove the white pith from the center.","Muddle the lime and sugar firmly in a rocks glass until the sugar dissolves into the juice.","Fill the glass with crushed ice.","Add the cachaça and stir well, pulling the limes up through the ice."]}],
["Caipiroska","Classic","rocks","custom","#e8f2c0","Vodka","A Caipirinha with vodka.",
 ["2|oz|Vodka","1|whole|Lime||cut into 8 wedges","2|tsp|Sugar"],"Lime wedge",
 {steps:["Cut the lime into wedges.","Muddle lime and sugar in a rocks glass until the sugar dissolves.","Fill with crushed ice, add vodka, and stir well."]}],
["Rum and Coke","Highball","highball","build","#4a2010","Rum","The simplest crowd-pleaser in the world: rum, Coke, ice. (Add lime and it becomes a Cuba Libre.)",
 ["2|oz|White Rum||or Spiced Rum or Dark Rum — all great","4|oz|Cola|top|Coca-Cola"],"Lime wedge (optional)"],

// ───────── HOT DRINKS ─────────
["Irish Coffee","Hot","irish","custom","#3a2213","Whiskey","Hot coffee, Irish whiskey, brown sugar and a lazy cloud of cream. Invented to warm frozen travelers in 1940s Ireland.",
 ["1.5|oz|Irish Whiskey","4|oz|Coffee||hot, freshly brewed","2|tsp|Brown Sugar","1|oz|Heavy Cream||lightly whipped"],"Floating cream (and a pinch of nutmeg if you're fancy)",
 {steps:["Preheat an Irish coffee glass or mug with hot water, then dump it.","Add the brown sugar and pour in the hot coffee. Stir until the sugar dissolves.","Stir in the Irish whiskey.","Lightly whip the cream (shake it in a jar for 10–15 seconds until it just thickens but still pours).","Pour the cream slowly over the back of a warm spoon so it floats on top. Do NOT stir — sip the coffee through the cream."]}],
["Hot Toddy","Hot","hot","custom","#c8862e","Whiskey","Whiskey, honey, lemon and hot water. The medicinal hug.",
 ["2|oz|Whiskey||bourbon, Irish or any whiskey","0.75|oz|Honey Syrup","0.5|oz|Lemon Juice","4|oz|Hot Water"],"Lemon wheel studded with cloves, cinnamon stick",
 {steps:["Preheat a mug with hot water and dump it out.","Add honey syrup and lemon juice.","Pour in the whiskey and top with hot (not boiling) water.","Stir and garnish with a clove-studded lemon wheel and cinnamon stick."]}],
["Hot Buttered Rum","Hot","hot","custom","#c8853a","Rum","Spiced butter batter melted into rum and hot water. Cozy Colonial-era decadence.",
 ["2|oz|Dark Rum","1|tbsp|Butter||softened","1|tbsp|Brown Sugar","1|pinch|Cinnamon","1|pinch|Nutmeg","4|oz|Hot Water"],"Cinnamon stick",
 {steps:["Mash the softened butter with brown sugar, cinnamon and nutmeg into a paste (the 'batter').","Spoon the batter into a warmed mug.","Add the rum and top with hot water.","Stir until the butter melts completely. Garnish with a cinnamon stick."]}],
["Mulled Wine","Hot","hot","custom","#6a1424","Wine","Glühwein! Red wine simmered with orange, spices and a splash of brandy. Smells like the holidays.",
 ["25|oz|Red Wine||one 750 ml bottle","2|oz|Brandy","0.25|cup|Sugar||or honey, to taste","1|whole|Orange||sliced","4|whole|Whole Cloves","2|whole|Cinnamon Stick","2|whole|Star Anise"],"Orange slice and cinnamon stick",
 {steps:["Add everything to a large pot.","Warm over low heat for 15–20 minutes — do NOT boil (you'll cook off the alcohol and make it bitter).","Taste and adjust sweetness.","Ladle into mugs, straining out the spices. Serves 4–6."]}],
["Wassail","Hot","hot","custom","#b86a2a","Brandy","Ancient English yuletide punch of hot spiced cider and juice. 'Waes hael!' means 'be well!'",
 ["32|oz|Apple Cider","16|oz|Orange Juice","4|oz|Lemon Juice","0.25|cup|Brown Sugar","3|whole|Cinnamon Stick","6|whole|Whole Cloves","2|whole|Star Anise","1|pinch|Nutmeg","6|oz|Brandy|opt|or Spiced Rum — leave out for kid-friendly"],"Orange slices studded with cloves, cinnamon stick",
 {steps:["Combine cider, orange juice, lemon juice and brown sugar in a large pot.","Add cinnamon sticks, cloves, star anise and nutmeg.","Simmer gently on low for 30–45 minutes, letting your house smell incredible.","Strain out the spices. Stir in brandy or rum just before serving if you're making it boozy.","Ladle into mugs and shout 'Wassail!' Serves 8–10."]}],
["Spiked Hot Chocolate","Hot","hot","custom","#4a2414","Liqueur","Rich hot cocoa with a minty boozy kick.",
 ["6|oz|Hot Chocolate||prepared","1.5|oz|Peppermint Schnapps","1|oz|Heavy Cream|opt|whipped"],"Whipped cream and crushed candy cane",
 {steps:["Make your hot chocolate in a mug.","Stir in the peppermint schnapps.","Top with whipped cream and a sprinkle of crushed candy cane."]}],
["Eggnog","Punch","hot","custom","#f1e3b8","Brandy","Rich, creamy, nutmeg-dusted holiday classic with bourbon, rum or brandy.",
 ["1|whole|Whole Egg","0.75|oz|Simple Syrup","2|oz|Milk","1|oz|Heavy Cream","1|oz|Brandy","1|oz|Bourbon||or Dark Rum"],"Freshly grated nutmeg",
 {steps:["Add everything to a shaker and dry shake (no ice) for 15 seconds to emulsify the egg.","Add ice and shake for another 15 seconds.","Strain into a chilled glass or mug.","Grate fresh nutmeg on top."]}],

// ───────── SHOTS ─────────
["Jello Shots","Shot","shot","custom","#e2304a","Vodka","Wobbly party jewels. Makes about 16 shots.",
 ["1|box|Gelatin Mix||3 oz flavored Jell-O","8|oz|Hot Water||boiling","4|oz|Vodka||chilled","4|oz|Cold Water"],"Whipped cream dollop (optional)",
 {steps:["Set out 16 small 1–2 oz plastic shot cups on a tray.","Whisk the Jell-O powder into 1 cup boiling water for 2 minutes until fully dissolved.","Stir in ½ cup cold water and ½ cup cold vodka (for stronger shots: ¼ cup water, ¾ cup vodka — any stronger and they won't set).","Pour into cups, filling about ¾ full.","Refrigerate at least 2–4 hours until firm. Squish and enjoy responsibly."],nodouble:1}],
["Lemon Drop Shot","Shot","shot","custom","#f4e26a","Vodka","Sugar-coated lemon, vodka chaser. Sweet and sour in one gulp.",
 ["1.5|oz|Citrus Vodka","1|wedge|Lemon","1|tsp|Sugar"],"Sugared lemon wedge",
 {steps:["Pour chilled citrus vodka into a shot glass.","Dip a lemon wedge in sugar.","Take the shot, then bite the sugared lemon."]}],
["B-52","Shot","shot","layer","#8a4a1e","Liqueur","Three perfect layers: coffee, cream, orange. Named after the bomber — or the band.",
 ["0.5|oz|Coffee Liqueur","0.5|oz|Irish Cream","0.5|oz|Grand Marnier"],"None"],
["Baby Guinness","Shot","shot","layer","#2a140a","Liqueur","Looks like a tiny pint of stout. Tastes like dessert.",
 ["1|oz|Coffee Liqueur","0.25|oz|Irish Cream"],"None"],
["Slippery Nipple","Shot","shot","layer","#e8dcc0","Liqueur","Sambuca and Irish cream in two silky layers. Name sold separately.",
 ["0.75|oz|Sambuca","0.75|oz|Irish Cream"],"None"],
["Buttery Nipple","Shot","shot","layer","#e8c98a","Liqueur","Butterscotch schnapps under Irish cream. Like a Werther's Original that went to college.",
 ["0.75|oz|Butterscotch Schnapps","0.75|oz|Irish Cream"],"None"],
["Green Tea Shot","Shot","shot","shake","#d0d880","Whiskey","No tea involved. Irish whiskey, peach schnapps and sour — tastes oddly like green tea.",
 ["0.5|oz|Irish Whiskey","0.5|oz|Peach Schnapps","0.5|oz|Sour Mix","1|splash|Lemon-Lime Soda"],"None"],
["Pickleback","Shot","shot","custom","#d0c890","Whiskey","A shot of whiskey chased by a shot of pickle brine. Brooklyn's best weird idea.",
 ["1.5|oz|Whiskey||Irish whiskey is traditional","1.5|oz|Pickle Brine"],"None",
 {steps:["Pour whiskey into one shot glass and pickle brine into another.","Shoot the whiskey.","Immediately chase with the pickle brine. The burn vanishes like magic."]}],
["Jägerbomb","Shot","shot","custom","#4a2a14","Liqueur","Drop a shot of Jäger into energy drink. Chug. Regret tomorrow.",
 ["1.5|oz|Jägermeister","4|oz|Energy Drink"],"None",
 {steps:["Pour energy drink into a pint or rocks glass.","Fill a shot glass with Jägermeister.","Drop the shot glass into the energy drink and drink immediately."]}],
["Washington Apple Shot","Shot","shot","shake","#b02a3a","Whiskey","Crown Royal, sour apple and cranberry. Tart and dangerously easy.",
 ["0.75|oz|Blended Whiskey||Crown Royal","0.75|oz|Sour Apple Schnapps","0.75|oz|Cranberry Juice"],"None"],
["Alabama Slammer","Highball","highball","shakeR","#e84a2a","Liqueur","Southern Comfort, sloe gin, amaretto and OJ. A college-bar legend.",
 ["1|oz|Southern Comfort","0.5|oz|Sloe Gin","0.5|oz|Amaretto","3|oz|Orange Juice"],"Orange slice and cherry"],

// ───────── PUNCH & BATCH ─────────
["Sangria","Punch","pitcher","custom","#7a1626","Wine","Spain's fruity red wine punch. Make it ahead — it gets better as it sits.",
 ["25|oz|Red Wine||one 750 ml bottle (Spanish Tempranillo or Garnacha)","3|oz|Brandy","2|oz|Triple Sec","4|oz|Orange Juice","2|oz|Simple Syrup","1|whole|Orange||sliced","1|whole|Apple||diced","1|whole|Lemon||sliced","6|oz|Club Soda|top|optional sparkle"],"Fruit from the pitcher",
 {steps:["Slice the orange and lemon into thin rounds and dice the apple.","Add the fruit to a large pitcher with brandy, triple sec and simple syrup. Muddle lightly.","Pour in the wine and orange juice, then stir well.","Refrigerate at least 2 hours (overnight is even better) so the fruit soaks it all up.","Serve over ice with a scoop of fruit in every glass. Top with soda for sparkle. Serves 6."],nodouble:1}],
["White Sangria","Punch","pitcher","custom","#f0e2a0","Wine","Crisp white wine with peaches, citrus and a splash of elderflower.",
 ["25|oz|White Wine||one bottle, dry","2|oz|Elderflower Liqueur","2|oz|Peach Schnapps","1|oz|Simple Syrup","1|whole|Lemon||sliced","1|whole|Peach||sliced","6|oz|Club Soda|top"],"Peach slices and mint",
 {steps:["Add the sliced fruit, elderflower, peach schnapps and syrup to a pitcher.","Pour in the wine and stir.","Chill at least 2 hours.","Serve over ice and top each glass with soda. Serves 6."],nodouble:1}],
["Fish House Punch","Punch","pitcher","custom","#d8963a","Rum","Philadelphia, 1732. George Washington reportedly lost three days to this punch.",
 ["12|oz|Dark Rum","8|oz|Cognac","2|oz|Peach Schnapps||or peach brandy","8|oz|Lemon Juice","6|oz|Simple Syrup","24|oz|Cold Water||or black tea"],"Lemon wheels and fresh nutmeg",
 {steps:["Combine all ingredients in a punch bowl and stir well.","Add a large block of ice (freeze water in a loaf pan the day before).","Chill 30 minutes.","Garnish with lemon wheels and grated nutmeg. Ladle into cups. Serves 12."],nodouble:1}],
["Polyjuice Potion","Geeky","potion","custom","#7ad04a","Vodka","Harry Potter's shapeshifting brew, muggle-style: lime sherbet, vodka and bubbling soda. Tastes far better than Goyle.",
 ["2|scoop|Lime Sherbet","1.5|oz|Vodka","2|dash|Angostura Bitters","4|oz|Lemon-Lime Soda|top"],"Gummy worms (they're 'lacewing flies')",
 {steps:["Put two scoops of lime sherbet into a glass, mug or potion bottle.","Pour the vodka and bitters over the sherbet.","Slowly top with lemon-lime soda — it'll foam up like a bubbling cauldron.","Stir gently until it turns a murky, magical green.","For a kid-safe version, skip the vodka. Drink before the effects wear off (one hour)."]}],
["Red Potion","Geeky","potion","custom","#c8203a","Rum","The Legend of Zelda heart-refill potion, from The Drunken Moogle. Restores all hearts (probably).",
 ["8|oz|Cran-Apple Juice","1.5|oz|Spiced Rum||Kraken Black Spiced Rum","0.5|oz|Tequila Blanco"],"Cork it in a potion bottle",
 {steps:["Fill a glass or potion bottle with ice.","Add the tequila first so its aroma doesn't overpower the drink.","Pour in the Kraken black spiced rum.","Top with the cran-apple juice and stir.","Hold it above your head and play the item-get jingle. Mandatory."]}],
["Lavender Town Syndrome","Geeky","collins","build","#a77ad6","Vodka","Eerie purple Pokémon cocktail from The Drunken Moogle, inspired by the ghost town. Serve while telling ghost stories.",
 ["2|oz|Hpnotiq","1|oz|Vodka||100 proof for an extra kick","0.25|oz|Grenadine","6|oz|Lemon-Lime Soda|top|Sprite"],"None — the creepy music is the garnish"],
["Butterbeer","Geeky","hot","custom","#d9a24a","Liqueur","A butterscotch-cream-soda treat with a foamy top. Spiked here with butterscotch schnapps — skip it for the kid version.",
 ["8|oz|Cream Soda","1|oz|Butterscotch Schnapps|opt","1|tbsp|Butterscotch Syrup","1|oz|Heavy Cream"],"Whipped butterscotch foam",
 {steps:["Whip the heavy cream with a little butterscotch syrup until it holds soft peaks.","Stir the rest of the butterscotch syrup (and schnapps) into the cream soda in a mug.","Spoon the butterscotch cream on top.","Drink like you just escaped a troll in the dungeon."]}],

// ───────── MORE GROWN-UP CLASSICS ─────────
["Brandy Alexander","Dessert","coupe","shake","#e3c79a","Brandy","Brandy, cacao and cream with nutmeg. A dessert in a coupe.",
 ["1.5|oz|Cognac","1|oz|Crème de Cacao||dark","1|oz|Heavy Cream"],"Freshly grated nutmeg"],
["Grasshopper","Dessert","coupe","shake","#9fdc9a","Liqueur","Mint chocolate chip ice cream in liquid form. Minty green and creamy.",
 ["1|oz|Crème de Menthe||green","1|oz|Crème de Cacao||white","1|oz|Heavy Cream"],"Mint leaf or chocolate shavings"],
["Pink Squirrel","Dessert","coupe","shake","#f2a8b8","Liqueur","Milwaukee, 1940s. Almond-y, pink, creamy, adorable.",
 ["1|oz|Crème de Noyaux","1|oz|Crème de Cacao||white","1|oz|Heavy Cream"],"Nutmeg"],
["Snaquiri","Shot","shot","shake","#eef0c8","Rum","A tiny Daiquiri shot — bartenders' secret handshake.",
 ["1|oz|White Rum","0.5|oz|Lime Juice","0.25|oz|Simple Syrup"],"None"],
["Shandy","Highball","pint","build","#f2d070","Beer","Half beer, half lemonade. Sunny afternoon in a pint glass.",
 ["8|oz|Lager Beer","8|oz|Lemonade|top"],"Lemon wheel",{nodouble:1}],
["Michelada","Highball","pint","custom","#c8622a","Beer","Mexico's savory beer cocktail: lime, hot sauce, Worcestershire and a chili-salt rim.",
 ["12|oz|Lager Beer||Mexican lager","1|oz|Lime Juice","2|dash|Hot Sauce","2|dash|Worcestershire Sauce","2|oz|Tomato Juice|opt|or Clamato"],"Tajín rim and lime wedge",
 {steps:["Rim a chilled pint glass with Tajín or chili-salt using a lime wedge.","Add lime juice, hot sauce, Worcestershire and tomato juice (if using).","Fill with ice and slowly top with the beer.","Stir gently and garnish with a lime wedge."],nodouble:1}],
["Black Velvet","Bubbly","flute","custom","#1e120a","Beer","Guinness and Champagne layered — created to mourn Prince Albert in 1861.",
 ["3|oz|Sparkling Wine","3|oz|Stout||Guinness"],"None",
 {steps:["Fill a flute halfway with Champagne.","Slowly pour the stout over the back of a spoon to layer on top."],nodouble:1}],

// ───────── MOCKTAILS ─────────
["Shirley Temple","Mocktail","highball","build","#f5728a","None","Ginger ale, grenadine and a cherry. The original kids'-menu classic.",
 ["6|oz|Ginger Ale||or Lemon-Lime Soda","0.5|oz|Grenadine"],"Maraschino cherries (lots)"],
["Roy Rogers","Mocktail","highball","build","#4a1a10","None","Cola with grenadine. The cowboy's Shirley Temple.",
 ["6|oz|Cola","0.5|oz|Grenadine"],"Maraschino cherry"],
["Arnold Palmer","Mocktail","collins","build","#c88a3a","None","Half iced tea, half lemonade. Named after the golf legend.",
 ["4|oz|Iced Tea","4|oz|Lemonade"],"Lemon wheel"],
["Virgin Mojito","Mocktail","collins","custom","#d8f0c0","None","All the mint and lime of a Mojito, none of the rum. A.k.a. the Nojito.",
 ["1|oz|Lime Juice","0.75|oz|Simple Syrup","8|leaves|Mint Leaves","5|oz|Club Soda|top"],"Mint sprig and lime wheel",
 {steps:["Gently muddle the mint with the syrup in a Collins glass.","Add lime juice and fill with crushed ice.","Top with club soda and swizzle.","Garnish with a slapped mint sprig and lime wheel."]}],
["Virgin Piña Colada","Mocktail","hurricane","blend","#f6eccc","None","Creamy pineapple-coconut bliss with no rum required.",
 ["4|oz|Pineapple Juice","2|oz|Coconut Cream","0.5|oz|Lime Juice|opt"],"Pineapple wedge and cherry"],
["Virgin Mary","Mocktail","highball","custom","#b82a1c","None","All the brunch flavor of a Bloody Mary, minus the vodka.",
 ["5|oz|Tomato Juice","0.5|oz|Lemon Juice","2|dash|Worcestershire Sauce","2|dash|Hot Sauce","1|tsp|Horseradish|opt","1|pinch|Celery Salt","1|pinch|Black Pepper"],"Celery stalk and lemon wedge",
 {steps:["Rim a highball glass with celery salt and fill with ice.","Combine everything in a shaker and roll it back and forth between two tins.","Strain into the glass and garnish generously."]}],
["Virgin Margarita","Mocktail","margarita","shakeR","#e8f0b0","None","A zesty no-booze margarita with orange and agave. Salt rim stays!",
 ["1.5|oz|Lime Juice","1|oz|Orange Juice","0.75|oz|Agave Syrup","2|oz|Club Soda|top"],"Salt rim and lime wheel",{pre:["Salt the rim of the glass."]}],
["Lime Rickey","Mocktail","highball","build","#d8f2c8","None","A soda-fountain classic — fresh lime, sugar and fizz.",
 ["1|oz|Lime Juice","0.75|oz|Simple Syrup","6|oz|Club Soda|top"],"Lime wheel"],
["Cinderella","Mocktail","hurricane","shakeR","#f6b04a","None","A fairy-tale fruit punch of orange, pineapple and lemon with a splash of fizz.",
 ["2|oz|Orange Juice","2|oz|Pineapple Juice","1|oz|Lemon Juice","0.25|oz|Grenadine","2|oz|Club Soda|top"],"Orange slice and cherry"],
["Ginger Mule Mocktail","Mocktail","mule","build","#e7d8a0","None","All the ginger zing of a Moscow Mule, no vodka needed.",
 ["1|oz|Lime Juice","0.25|oz|Simple Syrup","6|oz|Ginger Beer|top"],"Lime wheel and mint"],
["Lavender Lemonade","Mocktail","collins","build","#c8b2e6","None","Floral, tart and pastel purple.",
 ["1.5|oz|Lemon Juice","1|oz|Lavender Syrup","5|oz|Cold Water|top|or Club Soda for fizz"],"Lemon wheel and lavender sprig"],
["Strawberry Lemonade","Mocktail","collins","custom","#f27a8a","None","Fresh strawberries muddled into tart lemonade.",
 ["4|whole|Strawberries","1.5|oz|Lemon Juice","1|oz|Simple Syrup","5|oz|Cold Water"],"Strawberry and lemon wheel",
 {steps:["Muddle the strawberries with simple syrup in a shaker.","Add lemon juice and water, fill with ice and shake.","Strain (or don't, for pulp) into an ice-filled glass."]}],
["Phony Paloma","Mocktail","highball","build","#f4b8a8","None","A booze-free Paloma with grapefruit, lime and a salty rim.",
 ["2|oz|Grapefruit Juice","0.5|oz|Lime Juice","0.25|oz|Agave Syrup","4|oz|Grapefruit Soda|top"],"Salt rim and grapefruit wedge",{pre:["Rim the glass with salt."]}],
["Espresso Tonic","Mocktail","highball","custom","#6a3e1e","None","Bitter, bubbly, caffeinated. The barista's summer secret.",
 ["5|oz|Tonic Water","1.5|oz|Espresso||freshly brewed"],"Orange or lemon peel",
 {steps:["Fill a highball glass with ice and add the tonic.","Slowly pour the fresh espresso over the back of a spoon so it floats in a dramatic layer.","Garnish with a citrus peel. Stir before sipping, or don't."]}],
["Hot Apple Cider","Mocktail","hot","custom","#b8702a","None","Warm spiced cider — fall in a mug.",
 ["8|oz|Apple Cider","1|whole|Cinnamon Stick","2|whole|Whole Cloves","1|whole|Star Anise|opt"],"Cinnamon stick and apple slice",
 {steps:["Warm the cider with the spices in a small saucepan over medium-low heat for 10 minutes.","Strain into a mug and garnish with a cinnamon stick."]}],
["Root Beer Float","Mocktail","pint","custom","#5a2e14","None","A soda fountain icon: vanilla ice cream drowning in root beer foam.",
 ["2|scoop|Vanilla Ice Cream","8|oz|Root Beer"],"Whipped cream and a cherry",
 {steps:["Chill a tall glass in the freezer.","Add two scoops of vanilla ice cream.","Slowly pour the root beer over the top — go slow or the foam will escape!","Serve with a long spoon and a straw."]}],
["Cucumber Mint Cooler","Mocktail","collins","custom","#d4efcc","None","Spa-day refreshment: cucumber, mint, lime and soda.",
 ["4|slice|Cucumber","6|leaves|Mint Leaves","0.75|oz|Lime Juice","0.75|oz|Simple Syrup","5|oz|Club Soda|top"],"Cucumber ribbon",
 {steps:["Muddle the cucumber and mint with the simple syrup in a glass.","Add lime juice and fill with ice.","Top with club soda and stir gently."]}],
["Italian Soda","Mocktail","collins","build","#f08aa0","None","Flavored syrup, sparkling water and a cloud of cream. Pick any flavor.",
 ["1.5|oz|Raspberry Syrup||or any flavored syrup","8|oz|Club Soda","1|oz|Half & Half|opt|for a cremosa"],"Whipped cream"],
["Dirty Shirley","Highball","highball","build","#f26a82","Vodka","A grown-up Shirley Temple with vodka. Pure nostalgia with a kick.",
 ["1.5|oz|Vodka","5|oz|Lemon-Lime Soda|top","0.75|oz|Grenadine"],"Lots of maraschino cherries"]
);

/* ───────── SPOOKY SEASON ───────── */
window.DRINKS.push(
["El Diablo","Spooky","highball","shakeR","#8a1d3a","Tequila","A devilish 1940s Trader Vic classic: tequila, blackcurrant and lime under a fiery ginger beer cap.",
 ["1.5|oz|Tequila Reposado","0.5|oz|Crème de Cassis","0.5|oz|Lime Juice","3|oz|Ginger Beer|top"],"Lime wedge"],
["Satan's Whiskers","Spooky","coupe","shake","#e8822e","Gin","A Savoy Cocktail Book classic with a wicked name — gin, both vermouths, orange and Grand Marnier.",
 ["0.75|oz|Gin","0.75|oz|Sweet Vermouth","0.75|oz|Dry Vermouth","0.75|oz|Orange Juice","0.5|oz|Grand Marnier","1|dash|Orange Bitters"],"Orange twist"],
["Devil's Margarita","Spooky","coupe","shake","#7a1424","Tequila","A classic margarita haunted by a blood-red float of wine.",
 ["1.5|oz|Tequila Blanco","1|oz|Lime Juice","0.75|oz|Simple Syrup","0.5|oz|Red Wine|float|dry, fruity"],"Lime wheel"],
["Corpse Reviver #1","Spooky","coupe","stir","#9c4a1f","Brandy","The brooding, brandy-based older sibling of the #2 — a 'hair of the dog' from the 1930s.",
 ["1.5|oz|Cognac","0.75|oz|Apple Brandy||Calvados or applejack","0.75|oz|Sweet Vermouth"],"Orange peel"],
["Jack-O'-Lantern","Spooky","rocks","shakeR","#f08a24","Brandy","Glowing pumpkin-orange: cognac, orange liqueur and OJ topped with ginger ale. (House spec.)",
 ["1.5|oz|Cognac","0.5|oz|Grand Marnier","1|oz|Orange Juice","2|oz|Ginger Ale|top"],"Orange slice carved like a jack-o'-lantern"],
["Brain Hemorrhage","Spooky","shot","custom","#f2b8a0","Liqueur","The gross-out party shot: Irish cream curdles into a 'brain', grenadine adds the gore. Tastes like peaches & cream.",
 ["1|oz|Peach Schnapps","0.25|oz|Irish Cream","3|drop|Grenadine"],"None — it's gross enough",
 {steps:["Pour the peach schnapps into a shot glass.","Very slowly drizzle the Irish cream over the back of a spoon — it clumps into a wrinkly little brain.","Drip the grenadine in last so it bleeds down through the brain.","Show it to your friends. Watch them recoil. Drink it."]}],
["Candy Corn Shot","Spooky","shot","layer","#f5a623","Liqueur","Three-layer shot striped exactly like the Halloween candy everyone pretends to hate.",
 ["0.5|oz|Grenadine","0.5|oz|Orange Curaçao","0.5|oz|Heavy Cream"],"None"],
["Vampire's Kiss","Spooky","flute","build","#a3123a","Vodka","Blood-red bubbly with a raspberry bite and a sugar rim that sparkles like fangs. (House build.)",
 ["1|oz|Vodka","0.5|oz|Raspberry Liqueur","3|oz|Sparkling Wine|top"],"Red sugar rim",{pre:["Wet the rim with a lemon wedge and dip it in red sugar (or drip grenadine down the inside for a 'bleeding' look)."]}],
["Witch's Brew Punch","Spooky","pitcher","custom","#6ac43a","Vodka","A bubbling green cauldron punch for Halloween parties. Serves about 8.",
 ["6|oz|Vodka","6|oz|Melon Liqueur","16|oz|Pineapple Juice","3|oz|Lime Juice","24|oz|Lemon-Lime Soda|top","4|scoop|Lime Sherbet"],"Gummy worms and a floating 'ice hand'",
 {serves:8,nodouble:1,steps:["The day before: fill a food-safe glove with water, tie it off and freeze it for a creepy floating ice hand.","Stir the vodka, melon liqueur, pineapple juice and lime juice in a punch bowl or cauldron. Chill.","Right before guests arrive, add the ice hand and scoops of lime sherbet.","Slowly pour in the lemon-lime soda — the sherbet foams up like a bubbling brew.","Hang gummy worms over the rim. For fog, set dry ice in a separate outer bowl with warm water — never in the drinks."]}],
["Poison Apple","Spooky","coupe","shake","#6a0e22","Brandy","Dark, glossy and tempting, like something an evil queen would offer. (House build.)",
 ["1.5|oz|Apple Brandy","0.5|oz|Crème de Cassis","0.5|oz|Lemon Juice","0.25|oz|Cinnamon Syrup","1|oz|Apple Cider"],"Black sugar rim and a thin apple slice",{pre:["Rim the glass with black sanding sugar."]}],
["The Haddonfield","Spooky","rocks","shakeR","#c27a2c","Whiskey","Bourbon, cider and maple, named for a quiet Illinois town where absolutely nothing bad happens on October 31st. (House build.)",
 ["2|oz|Bourbon","3|oz|Apple Cider","0.25|oz|Maple Syrup","2|dash|Angostura Bitters"],"Cinnamon stick and apple slice"],
["Black Widow","Spooky","coupe","shake","#2a0f1e","Vodka","Inky blackberry sour with a bite. Pretty, dark, a little dangerous. (House build.)",
 ["1.5|oz|Vodka","0.75|oz|Crème de Mûre","0.75|oz|Lime Juice","0.5|oz|Simple Syrup"],"Blackberry on a pick (the spider)"],
["Swamp Water","Spooky","highball","shakeR","#9cb83a","Liqueur","A real 1970s Chartreuse promo drink: green, herbal and murky like a bayou at midnight.",
 ["1.5|oz|Green Chartreuse","4|oz|Pineapple Juice","0.75|oz|Lime Juice"],"Lime wheel"],
["Graveyard Dirt Martini","Spooky","martini","shake","#4a2c1c","Vodka","A chocolate martini buried in Oreo 'dirt' with worms crawling out. Dessert from the grave. (House build.)",
 ["1.5|oz|Vodka","1|oz|Crème de Cacao","1|oz|Irish Cream"],"Crushed Oreo rim and gummy worms",{pre:["Dip the rim in chocolate syrup, then in crushed Oreos."]}],
["Pumpkin Spice White Russian","Spooky","rocks","build","#e2b07a","Vodka","The Dude goes to a pumpkin patch.",
 ["1.5|oz|Vodka","1|oz|Coffee Liqueur","0.5|oz|Pumpkin Spice Syrup","1.5|oz|Heavy Cream|float"],"Pinch of cinnamon on top"],
["Bubbling Cauldron","Spooky","potion","custom","#7ad04a","None","Zero-proof witch's brew for the little monsters (and designated drivers).",
 ["2|scoop|Lime Sherbet","3|oz|Pineapple Juice","4|oz|Lemon-Lime Soda|top"],"Gummy worms",
 {steps:["Scoop the lime sherbet into a glass or potion bottle.","Pour in the pineapple juice.","Slowly top with lemon-lime soda and watch it foam over like a cauldron.","Hang a gummy worm over the edge."]}],
["Ghost Float","Spooky","pint","custom","#f4ecd8","None","A spooky-cute zero-proof float with a little ghost face.",
 ["2|scoop|Vanilla Ice Cream","8|oz|Cream Soda"],"Mini chocolate chips for ghost eyes",
 {steps:["Chill a tall glass.","Add two scoops of vanilla ice cream.","Slowly pour in the cream soda.","Press two mini chocolate chips into the top scoop for ghost eyes. Boo."]}]
);
/* batch-size info for big-batch recipes */
(() => { const S = {"Sangria":6,"White Sangria":6,"Fish House Punch":12,"Wassail":8,"Mulled Wine":5,"Jello Shots":16};
  window.DRINKS.forEach(r => { if (S[r[0]]) { r[9] = r[9] || {}; r[9].serves = S[r[0]]; } }); })();
